### PR TITLE
Remove Core usage

### LINKED ISSUE #12: Remove call to Hoa\Core
Still have dependencies to Hoa\Core in binary Praspel.php

```sh
Bin/Praspel.php
60:use Hoa\Core;
65:Core::enableErrorHandler();
66:Core::enableExceptionHandler();
88:catch ( Core\Exception $e ) {

Bin/Command/Generate.php
40:use Hoa\Core;
140:        $phpBinary = Core::getPHPBinary() ?:
147:        $envVariable   = '__ATOUM_PRASPEL_EXTENSION_' . md5(Core::uuid());
151:        $reflectionner->on('input', function ( Core\Event\Bucket $bucket )
166:        $reflectionner->on('output', function ( \Hoa\Core\Event\Bucket $bucket )

Exception.php
42: * Extending the \Hoa\Core\Exception class.
49:class Exception extends \Hoa\Core\Exception { }

Autoloader.php
46:if(is_file($vendorAutoloader = $vendorDirectory . '/hoa/core/Core.php'))
47:    require_once $vendorDirectory . '/hoa/core/Core.php';
55:    ->addDirectory('Hoa\Core', $vendorDirectory . '/hoa/core')

Praspel/Generator.php
40:use Hoa\Core;
150:            catch ( Core\Exception $e ) {
223:            catch ( Core\Exception $e ) {
```
Replace Core usage in files 

- [x] Bin/Praspel.php
- [x] Bin/Command/Generate.php
- [x] Exception.php
- [x] Autoloader.php
- [x] Praspel/Generator.php

Use `Hoa\Exception\Idle::enableUncaughtHandler` for exceptions
Use `Hoa\Exception\Error::enableErrorHandler` for errors

### PR DESCRIPTION
**Pull request by vonglasow**
Fix #12

### CODE REVIEW

**Comment by Hywan** [comment]
@vonglasow Use this opportunity to run `hoa devtools:cs` too please.

**Comment by vonglasow** [comment]
@Hywan To review and tests.

**Comment by Hywan** [comment]
Ready?

**Comment by vonglasow** [comment]
Not yet, during my tests, I have seen an issue regarding autoloading. I will see it soon!

**Comment by vonglasow** [comment]
wait for https://github.com/hoaproject/Praspel/pull/19

**Comment by vonglasow** [comment]
This patch fix the problem with Hoa\Core but still problem with `Hoa\Consistency\Xcallable`

**Comment by Hywan** [comment]
Thanks you! The new snapshot 0.16.06.06 has been released (https://github.com/hoaproject/Contributions-Atoum-PraspelExtension/releases/tag/0.16.06.06)!

**Pull request merged**
